CREATE TABLE [dbo].[DB_VERSIE] (
	[MAJOR] [char] (2) COLLATE Latin1_General_BIN NOT NULL ,
	[MINOR] [char] (2) COLLATE Latin1_General_BIN NOT NULL ,
	[RELEASE] [char] (2) COLLATE Latin1_General_BIN NOT NULL ,
	[BUILD] [char] (2) COLLATE Latin1_General_BIN NOT NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[DOCENT] (
	[DOCENTCODE] [char] (5) COLLATE Latin1_General_BIN NOT NULL ,
	[NAAM] [char] (32) COLLATE Latin1_General_BIN NULL ,
	[VOORNAAM] [char] (16) COLLATE Latin1_General_BIN NULL ,
	[ADRES] [char] (32) COLLATE Latin1_General_BIN NULL ,
	[POSTCODE] [char] (6) COLLATE Latin1_General_BIN NULL ,
	[WOONPLAATS] [char] (32) COLLATE Latin1_General_BIN NULL ,
	[TELEFOON] [char] (12) COLLATE Latin1_General_BIN NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[JAARGANG] (
	[LEERLINGNR] [char] (12) COLLATE Latin1_General_BIN NOT NULL ,
	[SCHOOLJAAR] [char] (4) COLLATE Latin1_General_BIN NOT NULL ,
	[KLAS] [char] (16) COLLATE Latin1_General_BIN NOT NULL ,
	[START] [datetime] NOT NULL ,
	[RELATIESTATUS] [char] (1) COLLATE Latin1_General_BIN NULL ,
	[VERBREEK] [datetime] NULL ,
	[ESF] [char] (1) COLLATE Latin1_General_BIN NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[KLASSEN] (
	[KLAS] [char] (16) COLLATE Latin1_General_BIN NOT NULL ,
	[TITEL] [char] (32) COLLATE Latin1_General_BIN NULL ,
	[UNIT] [char] (4) COLLATE Latin1_General_BIN NULL ,
	[LOKATIE] [char] (6) COLLATE Latin1_General_BIN NULL ,
	[ESFKLAS] [char] (1) COLLATE Latin1_General_BIN NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[LEERLING] (
	[LEERLINGNR] [char] (12) COLLATE Latin1_General_BIN NOT NULL ,
	[NAAM] [char] (32) COLLATE Latin1_General_BIN NULL ,
	[VOORNAAM] [char] (32) COLLATE Latin1_General_BIN NULL ,
	[ADRES] [char] (40) COLLATE Latin1_General_BIN NULL ,
	[POSTCODE] [char] (12) COLLATE Latin1_General_BIN NULL ,
	[WOONPLAATS] [char] (32) COLLATE Latin1_General_BIN NULL ,
	[TELEFOON] [char] (20) COLLATE Latin1_General_BIN NULL ,
	[GEBDAT] [datetime] NULL ,
	[GESLACHT] [char] (1) COLLATE Latin1_General_BIN NULL ,
	[INSCHRIJF] [datetime] NULL ,
	[UITSCHRIJF] [datetime] NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[LESJAAR] (
	[SCHOOLJAAR] [char] (4) COLLATE Latin1_General_BIN NOT NULL ,
	[TITEL] [char] (32) COLLATE Latin1_General_BIN NULL ,
	[BEGINDATUM] [datetime] NULL ,
	[EINDDATUM] [datetime] NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[LESROOSTER] (
	[DATUM] [datetime] NOT NULL ,
	[KLAS] [char] (16) COLLATE Latin1_General_BIN NOT NULL ,
	[BASIS] [char] (1) COLLATE Latin1_General_BIN NOT NULL ,
	[DOCENT1] [char] (5) COLLATE Latin1_General_BIN NULL ,
	[VAK1] [char] (8) COLLATE Latin1_General_BIN NULL ,
	[DOCENT2] [char] (5) COLLATE Latin1_General_BIN NULL ,
	[VAK2] [char] (8) COLLATE Latin1_General_BIN NULL ,
	[DOCENT3] [char] (5) COLLATE Latin1_General_BIN NULL ,
	[VAK3] [char] (8) COLLATE Latin1_General_BIN NULL ,
	[DOCENT4] [char] (5) COLLATE Latin1_General_BIN NULL ,
	[VAK4] [char] (8) COLLATE Latin1_General_BIN NULL ,
	[DOCENT5] [char] (5) COLLATE Latin1_General_BIN NULL ,
	[VAK5] [char] (8) COLLATE Latin1_General_BIN NULL ,
	[DOCENT6] [char] (5) COLLATE Latin1_General_BIN NULL ,
	[VAK6] [char] (8) COLLATE Latin1_General_BIN NULL ,
	[DOCENT7] [char] (5) COLLATE Latin1_General_BIN NULL ,
	[VAK7] [char] (8) COLLATE Latin1_General_BIN NULL ,
	[DOCENT8] [char] (5) COLLATE Latin1_General_BIN NULL ,
	[VAK8] [char] (8) COLLATE Latin1_General_BIN NULL ,
	[DOCENT9] [char] (5) COLLATE Latin1_General_BIN NULL ,
	[VAK9] [char] (8) COLLATE Latin1_General_BIN NULL ,
	[DOCENT10] [char] (5) COLLATE Latin1_General_BIN NULL ,
	[VAK10] [char] (8) COLLATE Latin1_General_BIN NULL ,
	[DOCENT11] [char] (5) COLLATE Latin1_General_BIN NULL ,
	[VAK11] [char] (8) COLLATE Latin1_General_BIN NULL ,
	[DOCENT12] [char] (5) COLLATE Latin1_General_BIN NULL ,
	[VAK12] [char] (8) COLLATE Latin1_General_BIN NULL ,
	[DOCENT13] [char] (5) COLLATE Latin1_General_BIN NULL ,
	[VAK13] [char] (8) COLLATE Latin1_General_BIN NULL ,
	[DOCENT14] [char] (5) COLLATE Latin1_General_BIN NULL ,
	[VAK14] [char] (8) COLLATE Latin1_General_BIN NULL ,
	[DOCENT15] [char] (5) COLLATE Latin1_General_BIN NULL ,
	[VAK15] [char] (8) COLLATE Latin1_General_BIN NULL ,
	[DOCENT16] [char] (5) COLLATE Latin1_General_BIN NULL ,
	[VAK16] [char] (8) COLLATE Latin1_General_BIN NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[LOG] (
	[DATUM] [datetime] NULL ,
	[LOGIN] [char] (10) COLLATE Latin1_General_BIN NULL ,
	[SCHOOLJAAR] [char] (4) COLLATE Latin1_General_BIN NULL ,
	[LOGTYPE] [char] (6) COLLATE Latin1_General_BIN NULL ,
	[OPMERKING] [char] (64) COLLATE Latin1_General_BIN NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[LOKATIES] (
	[LOKATIE] [char] (6) COLLATE Latin1_General_BIN NOT NULL ,
	[TITEL] [char] (32) COLLATE Latin1_General_BIN NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[MANAGEMENT] (
	[MAJOR] [char] (2) COLLATE Latin1_General_BIN NOT NULL ,
	[MINOR] [char] (2) COLLATE Latin1_General_BIN NOT NULL ,
	[RELEASE] [char] (2) COLLATE Latin1_General_BIN NOT NULL ,
	[BUILD] [char] (2) COLLATE Latin1_General_BIN NOT NULL ,
	[CLIENT_STATUS] [char] (4) COLLATE Latin1_General_BIN NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[ORGANISATIES] (
	[ORG_ID] [char] (12) COLLATE Latin1_General_BIN NOT NULL ,
	[TITEL] [char] (32) COLLATE Latin1_General_BIN NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[RELATIES] (
	[LEERLINGNR] [char] (12) COLLATE Latin1_General_BIN NOT NULL ,
	[ORG_ID] [char] (12) COLLATE Latin1_General_BIN NOT NULL ,
	[START] [datetime] NOT NULL ,
	[EIND] [datetime] NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[SECURITY] (
	[LOGIN] [char] (10) COLLATE Latin1_General_BIN NOT NULL ,
	[LOKATIE] [char] (6) COLLATE Latin1_General_BIN NOT NULL ,
	[SEC_LEVEL] [smallint] NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[STAGE] (
	[LEERLINGNR] [char] (12) COLLATE Latin1_General_BIN NOT NULL ,
	[DATUM] [datetime] NOT NULL ,
	[UREN] [smallint] NULL ,
	[BEDRIJF] [char] (32) COLLATE Latin1_General_BIN NULL ,
	[TELEFOON] [char] (12) COLLATE Latin1_General_BIN NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[STATUS] (
	[LEERLINGNR] [char] (12) COLLATE Latin1_General_BIN NOT NULL ,
	[DATUM] [datetime] NOT NULL ,
	[KLAS] [char] (16) COLLATE Latin1_General_BIN NOT NULL ,
	[STATUS1] [char] (1) COLLATE Latin1_General_BIN NULL ,
	[STATUS2] [char] (1) COLLATE Latin1_General_BIN NULL ,
	[STATUS3] [char] (1) COLLATE Latin1_General_BIN NULL ,
	[STATUS4] [char] (1) COLLATE Latin1_General_BIN NULL ,
	[STATUS5] [char] (1) COLLATE Latin1_General_BIN NULL ,
	[STATUS6] [char] (1) COLLATE Latin1_General_BIN NULL ,
	[STATUS7] [char] (1) COLLATE Latin1_General_BIN NULL ,
	[STATUS8] [char] (1) COLLATE Latin1_General_BIN NULL ,
	[STATUS9] [char] (1) COLLATE Latin1_General_BIN NULL ,
	[STATUS10] [char] (1) COLLATE Latin1_General_BIN NULL ,
	[STATUS11] [char] (1) COLLATE Latin1_General_BIN NULL ,
	[STATUS12] [char] (1) COLLATE Latin1_General_BIN NULL ,
	[STATUS13] [char] (1) COLLATE Latin1_General_BIN NULL ,
	[STATUS14] [char] (1) COLLATE Latin1_General_BIN NULL ,
	[STATUS15] [char] (1) COLLATE Latin1_General_BIN NULL ,
	[STATUS16] [char] (1) COLLATE Latin1_General_BIN NULL ,
	[OPMERKING] [char] (64) COLLATE Latin1_General_BIN NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[TEMP_DATA] (
	[LOGIN] [char] (10) COLLATE Latin1_General_BIN NOT NULL ,
	[DATUM] [datetime] NOT NULL ,
	[LEERLINGNR] [char] (12) COLLATE Latin1_General_BIN NULL ,
	[LLN_EXTRA] [char] (12) COLLATE Latin1_General_BIN NULL ,
	[NAAM] [char] (32) COLLATE Latin1_General_BIN NULL ,
	[VOORNAAM] [char] (32) COLLATE Latin1_General_BIN NULL ,
	[FULLNAME] [char] (48) COLLATE Latin1_General_BIN NULL ,
	[ADRES] [char] (40) COLLATE Latin1_General_BIN NULL ,
	[POSTCODE] [char] (12) COLLATE Latin1_General_BIN NULL ,
	[WOONPLAATS] [char] (32) COLLATE Latin1_General_BIN NULL ,
	[TELEFOON] [char] (20) COLLATE Latin1_General_BIN NULL ,
	[GEBDAT] [datetime] NULL ,
	[GESLACHT] [char] (1) COLLATE Latin1_General_BIN NULL ,
	[KLAS] [char] (16) COLLATE Latin1_General_BIN NULL ,
	[KLAS_TITEL] [char] (32) COLLATE Latin1_General_BIN NULL ,
	[UNIT] [char] (4) COLLATE Latin1_General_BIN NULL ,
	[UNIT_AFK] [char] (16) COLLATE Latin1_General_BIN NULL ,
	[UNIT_TITEL] [char] (64) COLLATE Latin1_General_BIN NULL ,
	[LOKATIE] [char] (6) COLLATE Latin1_General_BIN NULL ,
	[LOKATIE_TITEL] [char] (32) COLLATE Latin1_General_BIN NULL ,
	[SCHOOLJAAR] [char] (4) COLLATE Latin1_General_BIN NULL ,
	[SCHOOLJAAR_TITEL] [char] (32) COLLATE Latin1_General_BIN NULL ,
	[BEGINDATUM] [datetime] NULL ,
	[EINDDATUM] [datetime] NULL ,
	[ORG_ID] [char] (12) COLLATE Latin1_General_BIN NULL ,
	[ORG_TITEL] [char] (32) COLLATE Latin1_General_BIN NULL ,
	[ESF] [char] (1) COLLATE Latin1_General_BIN NULL ,
	[COUNTNR] [smallint] NULL ,
	[STATUS] [char] (1) COLLATE Latin1_General_BIN NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[UNITS] (
	[UNIT] [char] (4) COLLATE Latin1_General_BIN NOT NULL ,
	[AFKORTING] [char] (16) COLLATE Latin1_General_BIN NULL ,
	[TITEL] [char] (64) COLLATE Latin1_General_BIN NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[USERS] (
	[LOGIN] [char] (10) COLLATE Latin1_General_BIN NOT NULL ,
	[NAAM] [char] (32) COLLATE Latin1_General_BIN NULL ,
	[VOORNAAM] [char] (16) COLLATE Latin1_General_BIN NULL ,
	[PASSWRD] [char] (20) COLLATE Latin1_General_BIN NULL ,
	[ENCRYPTTYPE] [int] NULL ,
	[LOKATIE] [char] (6) COLLATE Latin1_General_BIN NULL ,
	[ACTIEF] [datetime] NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[VAKKEN] (
	[VAK] [char] (8) COLLATE Latin1_General_BIN NOT NULL ,
	[TITEL] [char] (32) COLLATE Latin1_General_BIN NULL ,
	[VAKTYPE] [char] (1) COLLATE Latin1_General_BIN NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[XLINK] (
	[XFIELD] [char] (32) COLLATE Latin1_General_BIN NOT NULL ,
	[XVALUE] [char] (8) COLLATE Latin1_General_BIN NOT NULL ,
	[SHORTDESCR] [char] (8) COLLATE Latin1_General_BIN NULL ,
	[DESCR32] [char] (32) COLLATE Latin1_General_BIN NULL 
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[DB_VERSIE] ADD 
	CONSTRAINT [PK_DB_VERSIE] PRIMARY KEY  NONCLUSTERED 
	(
		[MAJOR],
		[MINOR],
		[RELEASE],
		[BUILD]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[DOCENT] ADD 
	CONSTRAINT [PK_DOCENT] PRIMARY KEY  NONCLUSTERED 
	(
		[DOCENTCODE]
	)  ON [PRIMARY] 
GO

 CREATE  INDEX [DOCENT_0] ON [dbo].[DOCENT]([DOCENTCODE]) ON [PRIMARY]
GO

 CREATE  UNIQUE  INDEX [DOCENT_MAIN] ON [dbo].[DOCENT]([DOCENTCODE]) ON [PRIMARY]
GO

ALTER TABLE [dbo].[JAARGANG] ADD 
	CONSTRAINT [PK_JAARGANG] PRIMARY KEY  NONCLUSTERED 
	(
		[LEERLINGNR],
		[SCHOOLJAAR],
		[KLAS],
		[START]
	)  ON [PRIMARY] 
GO

 CREATE  INDEX [JAARGANG_0] ON [dbo].[JAARGANG]([LEERLINGNR]) ON [PRIMARY]
GO

 CREATE  INDEX [JAARGANG_1] ON [dbo].[JAARGANG]([KLAS]) ON [PRIMARY]
GO

 CREATE  UNIQUE  INDEX [JAARGANG_MAIN] ON [dbo].[JAARGANG]([LEERLINGNR], [SCHOOLJAAR], [KLAS], [START]) ON [PRIMARY]
GO

ALTER TABLE [dbo].[KLASSEN] ADD 
	CONSTRAINT [PK_KLASSEN] PRIMARY KEY  NONCLUSTERED 
	(
		[KLAS]
	)  ON [PRIMARY] 
GO

 CREATE  INDEX [KLASSEN_0] ON [dbo].[KLASSEN]([KLAS]) ON [PRIMARY]
GO

 CREATE  INDEX [KLASSEN_1] ON [dbo].[KLASSEN]([UNIT]) ON [PRIMARY]
GO

 CREATE  UNIQUE  INDEX [KLASSEN_MAIN] ON [dbo].[KLASSEN]([KLAS]) ON [PRIMARY]
GO

ALTER TABLE [dbo].[LEERLING] ADD 
	CONSTRAINT [PK_LEERLING] PRIMARY KEY  NONCLUSTERED 
	(
		[LEERLINGNR]
	)  ON [PRIMARY] 
GO

 CREATE  INDEX [LEERLING_0] ON [dbo].[LEERLING]([LEERLINGNR]) ON [PRIMARY]
GO

 CREATE  UNIQUE  INDEX [LEERLING_MAIN] ON [dbo].[LEERLING]([LEERLINGNR]) ON [PRIMARY]
GO

ALTER TABLE [dbo].[LESJAAR] ADD 
	CONSTRAINT [PK_LESJAAR] PRIMARY KEY  NONCLUSTERED 
	(
		[SCHOOLJAAR]
	)  ON [PRIMARY] 
GO

 CREATE  UNIQUE  INDEX [LESJAAR_MAIN] ON [dbo].[LESJAAR]([SCHOOLJAAR]) ON [PRIMARY]
GO

ALTER TABLE [dbo].[LESROOSTER] ADD 
	CONSTRAINT [PK_LESROOSTER] PRIMARY KEY  NONCLUSTERED 
	(
		[DATUM],
		[KLAS],
		[BASIS]
	)  ON [PRIMARY] 
GO

 CREATE  INDEX [LESROOSTER_0] ON [dbo].[LESROOSTER]([DATUM]) ON [PRIMARY]
GO

 CREATE  INDEX [LESROOSTER_1] ON [dbo].[LESROOSTER]([KLAS]) ON [PRIMARY]
GO

 CREATE  INDEX [LESROOSTER_10] ON [dbo].[LESROOSTER]([VAK9]) ON [PRIMARY]
GO

 CREATE  INDEX [LESROOSTER_11] ON [dbo].[LESROOSTER]([VAK10]) ON [PRIMARY]
GO

 CREATE  INDEX [LESROOSTER_12] ON [dbo].[LESROOSTER]([VAK11]) ON [PRIMARY]
GO

 CREATE  INDEX [LESROOSTER_13] ON [dbo].[LESROOSTER]([VAK12]) ON [PRIMARY]
GO

 CREATE  INDEX [LESROOSTER_14] ON [dbo].[LESROOSTER]([VAK13]) ON [PRIMARY]
GO

 CREATE  INDEX [LESROOSTER_15] ON [dbo].[LESROOSTER]([VAK14]) ON [PRIMARY]
GO

 CREATE  INDEX [LESROOSTER_16] ON [dbo].[LESROOSTER]([VAK15]) ON [PRIMARY]
GO

 CREATE  INDEX [LESROOSTER_17] ON [dbo].[LESROOSTER]([VAK16]) ON [PRIMARY]
GO

 CREATE  INDEX [LESROOSTER_2] ON [dbo].[LESROOSTER]([VAK1]) ON [PRIMARY]
GO

 CREATE  INDEX [LESROOSTER_3] ON [dbo].[LESROOSTER]([VAK2]) ON [PRIMARY]
GO

 CREATE  INDEX [LESROOSTER_4] ON [dbo].[LESROOSTER]([VAK3]) ON [PRIMARY]
GO

 CREATE  INDEX [LESROOSTER_5] ON [dbo].[LESROOSTER]([VAK4]) ON [PRIMARY]
GO

 CREATE  INDEX [LESROOSTER_6] ON [dbo].[LESROOSTER]([VAK5]) ON [PRIMARY]
GO

 CREATE  INDEX [LESROOSTER_7] ON [dbo].[LESROOSTER]([VAK6]) ON [PRIMARY]
GO

 CREATE  INDEX [LESROOSTER_8] ON [dbo].[LESROOSTER]([VAK7]) ON [PRIMARY]
GO

 CREATE  INDEX [LESROOSTER_9] ON [dbo].[LESROOSTER]([VAK8]) ON [PRIMARY]
GO

 CREATE  INDEX [LOG_MAIN] ON [dbo].[LOG]([DATUM], [LOGIN], [SCHOOLJAAR]) ON [PRIMARY]
GO

ALTER TABLE [dbo].[LOKATIES] ADD 
	CONSTRAINT [PK_LOKATIES] PRIMARY KEY  NONCLUSTERED 
	(
		[LOKATIE]
	)  ON [PRIMARY] 
GO

 CREATE  UNIQUE  INDEX [LOKATIES_MAIN] ON [dbo].[LOKATIES]([LOKATIE]) ON [PRIMARY]
GO

ALTER TABLE [dbo].[MANAGEMENT] ADD 
	CONSTRAINT [PK_MANAGEMENT] PRIMARY KEY  NONCLUSTERED 
	(
		[MAJOR],
		[MINOR],
		[RELEASE],
		[BUILD]
	)  ON [PRIMARY] 
GO

 CREATE  UNIQUE  INDEX [MANAGEMENT_MAIN] ON [dbo].[MANAGEMENT]([MAJOR], [MINOR], [RELEASE], [BUILD]) ON [PRIMARY]
GO

ALTER TABLE [dbo].[ORGANISATIES] ADD 
	CONSTRAINT [PK_ORGANISATIES] PRIMARY KEY  NONCLUSTERED 
	(
		[ORG_ID]
	)  ON [PRIMARY] 
GO

 CREATE  INDEX [ORG_0] ON [dbo].[ORGANISATIES]([ORG_ID]) ON [PRIMARY]
GO

 CREATE  UNIQUE  INDEX [ORG_MAIN] ON [dbo].[ORGANISATIES]([ORG_ID]) ON [PRIMARY]
GO

ALTER TABLE [dbo].[RELATIES] ADD 
	CONSTRAINT [PK_RELATIES] PRIMARY KEY  NONCLUSTERED 
	(
		[LEERLINGNR],
		[ORG_ID],
		[START]
	)  ON [PRIMARY] 
GO

 CREATE  INDEX [RELATIE_0] ON [dbo].[RELATIES]([LEERLINGNR]) ON [PRIMARY]
GO

 CREATE  INDEX [RELATIE_1] ON [dbo].[RELATIES]([ORG_ID]) ON [PRIMARY]
GO

 CREATE  UNIQUE  INDEX [RELATIE_MAIN] ON [dbo].[RELATIES]([LEERLINGNR], [ORG_ID], [START]) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SECURITY] ADD 
	CONSTRAINT [PK_SECURITY] PRIMARY KEY  NONCLUSTERED 
	(
		[LOGIN],
		[LOKATIE]
	)  ON [PRIMARY] 
GO

 CREATE  UNIQUE  INDEX [SECURITY_MAIN] ON [dbo].[SECURITY]([LOGIN], [LOKATIE]) ON [PRIMARY]
GO

ALTER TABLE [dbo].[STAGE] ADD 
	CONSTRAINT [PK_STAGE] PRIMARY KEY  NONCLUSTERED 
	(
		[LEERLINGNR],
		[DATUM]
	)  ON [PRIMARY] 
GO

 CREATE  INDEX [STAGE_0] ON [dbo].[STAGE]([LEERLINGNR]) ON [PRIMARY]
GO

 CREATE  INDEX [STAGE_1] ON [dbo].[STAGE]([DATUM]) ON [PRIMARY]
GO

 CREATE  UNIQUE  INDEX [STAGE_MAIN] ON [dbo].[STAGE]([LEERLINGNR], [DATUM]) ON [PRIMARY]
GO

ALTER TABLE [dbo].[STATUS] ADD 
	CONSTRAINT [PK_STATUS] PRIMARY KEY  NONCLUSTERED 
	(
		[LEERLINGNR],
		[DATUM],
		[KLAS]
	)  ON [PRIMARY] 
GO

 CREATE  INDEX [STATUS_0] ON [dbo].[STATUS]([LEERLINGNR]) ON [PRIMARY]
GO

 CREATE  INDEX [STATUS_1] ON [dbo].[STATUS]([DATUM]) ON [PRIMARY]
GO

 CREATE  INDEX [STATUS_2] ON [dbo].[STATUS]([KLAS]) ON [PRIMARY]
GO

 CREATE  INDEX [STATUS_KLAS] ON [dbo].[STATUS]([DATUM], [KLAS]) ON [PRIMARY]
GO

 CREATE  UNIQUE  INDEX [STATUS_MAIN] ON [dbo].[STATUS]([LEERLINGNR], [DATUM], [KLAS]) ON [PRIMARY]
GO

 CREATE  INDEX [TEMP_DATA_MAIN] ON [dbo].[TEMP_DATA]([LOGIN], [DATUM]) ON [PRIMARY]
GO

ALTER TABLE [dbo].[UNITS] ADD 
	CONSTRAINT [PK_UNITS] PRIMARY KEY  NONCLUSTERED 
	(
		[UNIT]
	)  ON [PRIMARY] 
GO

 CREATE  INDEX [UNITS_0] ON [dbo].[UNITS]([UNIT]) ON [PRIMARY]
GO

 CREATE  UNIQUE  INDEX [UNITS_MAIN] ON [dbo].[UNITS]([UNIT]) ON [PRIMARY]
GO

ALTER TABLE [dbo].[USERS] ADD 
	CONSTRAINT [PK_USERS] PRIMARY KEY  NONCLUSTERED 
	(
		[LOGIN]
	)  ON [PRIMARY] 
GO

 CREATE  UNIQUE  INDEX [USERS_MAIN] ON [dbo].[USERS]([LOGIN]) ON [PRIMARY]
GO

ALTER TABLE [dbo].[VAKKEN] ADD 
	CONSTRAINT [PK_VAKKEN] PRIMARY KEY  NONCLUSTERED 
	(
		[VAK]
	)  ON [PRIMARY] 
GO

 CREATE  INDEX [VAKKEN_0] ON [dbo].[VAKKEN]([VAK]) ON [PRIMARY]
GO

 CREATE  UNIQUE  INDEX [VAKKEN_MAIN] ON [dbo].[VAKKEN]([VAK]) ON [PRIMARY]
GO

ALTER TABLE [dbo].[XLINK] ADD 
	CONSTRAINT [PK_XLINK] PRIMARY KEY  NONCLUSTERED 
	(
		[XFIELD],
		[XVALUE]
	)  ON [PRIMARY] 
GO

 CREATE  INDEX [XLINK_0] ON [dbo].[XLINK]([XFIELD]) ON [PRIMARY]
GO

 CREATE  INDEX [XLINK_1] ON [dbo].[XLINK]([XVALUE]) ON [PRIMARY]
GO

 CREATE  UNIQUE  INDEX [XLINK_MAIN] ON [dbo].[XLINK]([XFIELD], [XVALUE]) ON [PRIMARY]
GO

SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO


/****** Object:  View dbo.STATUS_VW    Script Date: 4-12-2003 5:43:44 ******/
CREATE VIEW STATUS_VW AS
      SELECT LEERLINGNR, DATUM, KLAS, 'STATUS1'  AS VOLGNR, STATUS1  AS STATUS FROM STATUS WHERE STATUS1  IS NOT NULL AND STATUS1  <> ''
UNION SELECT LEERLINGNR, DATUM, KLAS, 'STATUS2'  AS VOLGNR, STATUS2  AS STATUS FROM STATUS WHERE STATUS2  IS NOT NULL AND STATUS2  <> ''
UNION SELECT LEERLINGNR, DATUM, KLAS, 'STATUS3'  AS VOLGNR, STATUS3  AS STATUS FROM STATUS WHERE STATUS3  IS NOT NULL AND STATUS3  <> ''
UNION SELECT LEERLINGNR, DATUM, KLAS, 'STATUS4'  AS VOLGNR, STATUS4  AS STATUS FROM STATUS WHERE STATUS4  IS NOT NULL AND STATUS4  <> ''
UNION SELECT LEERLINGNR, DATUM, KLAS, 'STATUS5'  AS VOLGNR, STATUS5  AS STATUS FROM STATUS WHERE STATUS5  IS NOT NULL AND STATUS5  <> ''
UNION SELECT LEERLINGNR, DATUM, KLAS, 'STATUS6'  AS VOLGNR, STATUS6  AS STATUS FROM STATUS WHERE STATUS6  IS NOT NULL AND STATUS6  <> ''
UNION SELECT LEERLINGNR, DATUM, KLAS, 'STATUS7'  AS VOLGNR, STATUS7  AS STATUS FROM STATUS WHERE STATUS7  IS NOT NULL AND STATUS7  <> ''
UNION SELECT LEERLINGNR, DATUM, KLAS, 'STATUS8'  AS VOLGNR, STATUS8  AS STATUS FROM STATUS WHERE STATUS8  IS NOT NULL AND STATUS8  <> ''
UNION SELECT LEERLINGNR, DATUM, KLAS, 'STATUS9'  AS VOLGNR, STATUS9  AS STATUS FROM STATUS WHERE STATUS9  IS NOT NULL AND STATUS9  <> ''
UNION SELECT LEERLINGNR, DATUM, KLAS, 'STATUS10' AS VOLGNR, STATUS10 AS STATUS FROM STATUS WHERE STATUS10 IS NOT NULL AND STATUS10 <> ''
UNION SELECT LEERLINGNR, DATUM, KLAS, 'STATUS11' AS VOLGNR, STATUS11 AS STATUS FROM STATUS WHERE STATUS11 IS NOT NULL AND STATUS11 <> ''
UNION SELECT LEERLINGNR, DATUM, KLAS, 'STATUS12' AS VOLGNR, STATUS12 AS STATUS FROM STATUS WHERE STATUS12 IS NOT NULL AND STATUS12 <> ''
UNION SELECT LEERLINGNR, DATUM, KLAS, 'STATUS13' AS VOLGNR, STATUS13 AS STATUS FROM STATUS WHERE STATUS13 IS NOT NULL AND STATUS13 <> ''
UNION SELECT LEERLINGNR, DATUM, KLAS, 'STATUS14' AS VOLGNR, STATUS14 AS STATUS FROM STATUS WHERE STATUS14 IS NOT NULL AND STATUS14 <> ''
UNION SELECT LEERLINGNR, DATUM, KLAS, 'STATUS15' AS VOLGNR, STATUS15 AS STATUS FROM STATUS WHERE STATUS15 IS NOT NULL AND STATUS15 <> ''
UNION SELECT LEERLINGNR, DATUM, KLAS, 'STATUS16' AS VOLGNR, STATUS16 AS STATUS FROM STATUS WHERE STATUS16 IS NOT NULL AND STATUS16 <> ''


GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

