USE SA76PRO
GO
SELECT DISTINCT A.OPRID, A.QRYNAME, A.DESCR, B.LANGUAGE_CD, B.OPRID AS OPRID_LNG, B.QRYNAME AS QRYNAME_LNG, B.DESCR AS DESCR_LNG FROM PSQRYDEFN A FULL OUTER JOIN PSQRYDEFNLANG B
  ON (A.OPRID   = B.OPRID
  AND A.QRYNAME = B.QRYNAME)
ORDER BY 1,2,3,4
GO
SELECT * FROM PSQRYBIND		WHERE OPRID = 'OVB' AND QRYNAME LIKE '%DHUI%'
SELECT * FROM PSQRYBINDLANG	WHERE OPRID = 'OVB' AND QRYNAME LIKE '%DHUI%'
SELECT * FROM PSQRYCRITERIA	WHERE OPRID = 'OVB' AND QRYNAME LIKE '%DHUI%'
SELECT * FROM PSQRYDEFN		WHERE OPRID = 'OVB' AND QRYNAME LIKE '%DHUI%'
SELECT * FROM PSQRYDEFNLANG	WHERE OPRID = 'OVB' AND QRYNAME LIKE '%DHUI%'
--SELECT TOP 5 * FROM PSQRYDEL		WHERE OPRID = 'OVB'
SELECT * FROM PSQRYEXPR		WHERE OPRID = 'OVB' AND QRYNAME LIKE '%DHUI%'
SELECT * FROM PSQRYFIELD		WHERE OPRID = 'OVB' AND QRYNAME LIKE '%DHUI%'
SELECT * FROM PSQRYFIELDLANG	WHERE OPRID = 'OVB' AND QRYNAME LIKE '%DHUI%'
--SELECT TOP 5 * FROM PSQRYLINK
SELECT * FROM PSQRYRECORD		WHERE OPRID = 'OVB' AND QRYNAME LIKE '%DHUI%'
  AND RECNAME IN (SELECT RECNAME FROM PSRECDEFN)
SELECT * FROM PSQRYSELECT		WHERE OPRID = 'OVB' AND QRYNAME LIKE '%DHUI%'


/*
SELECT * FROM PSQRYRECORD A
WHERE QRYNAME LIKE 'AC_STUD%'
*/
USE SA76TRN
SELECT TOP 5 * FROM PSTREENODE
WHERE TREE_NODE LIKE 'CITIZEN%'

USE SA76PRO
SELECT TOP 5 * FROM PSTREENODE
WHERE TREE_NODE = 'CAMPUS_TBL'

GO 
SELECT TOP 5 * FROM PS_ADDRESSES
