Database:  localhost:D:/Development/WebSite/_template.db/_data/_template.fdb, User: SYSDBA

SET SQL DIALECT 3;

/* CREATE DATABASE 'localhost:D:/Development/WebSite/_template.db/_data/_template.fdb' DEFAULT CHARACTER SET NONE */


/* Table: DB_BUILDING, Owner: SYSDBA */
CREATE TABLE DB_BUILDING (BUILDINGID VARCHAR(20) NOT NULL,
        EFFDT DATE NOT NULL,
        EFFSTATUS VARCHAR(6),
        COUNTRY VARCHAR(6),
        REGION VARCHAR(64),
        CITY VARCHAR(64),
        STREET VARCHAR(64),
        NR1 VARCHAR(12),
        NR2 VARCHAR(12),
        POSTAL VARCHAR(12),
        PERSIDCONTACT VARCHAR(20),
        BUILDINGCODE VARCHAR(32),
        DESCR VARCHAR(64),
        DESCRLONG VARCHAR(256),
        LASTUPDATEDTTM TIMESTAMP,
        LASTUPDATEOPRID VARCHAR(20),
PRIMARY KEY (BUILDINGID, EFFDT));

/* Table: DB_CITY, Owner: SYSDBA */
CREATE TABLE DB_CITY (COUNTRY VARCHAR(6) NOT NULL,
        REGION VARCHAR(64) NOT NULL,
        CITY VARCHAR(64) NOT NULL,
        EFFDT DATE NOT NULL,
        EFFSTATUS VARCHAR(6),
        DESCR VARCHAR(64),
        DESCRLONG VARCHAR(256),
        LASTUPDATEDTTM TIMESTAMP,
        LASTUPDATEOPRID VARCHAR(20),
PRIMARY KEY (COUNTRY, REGION, CITY, EFFDT));

/* Table: DB_COUNTRY, Owner: SYSDBA */
CREATE TABLE DB_COUNTRY (COUNTRY VARCHAR(6) NOT NULL,
        EFFDT DATE NOT NULL,
        EFFSTATUS VARCHAR(6),
        PHONECODE VARCHAR(12),
        DESCR VARCHAR(64),
        DESCRLONG VARCHAR(256),
        LASTUPDATEDTTM TIMESTAMP,
        LASTUPDATEOPRID VARCHAR(20),
PRIMARY KEY (COUNTRY, EFFDT));

/* Table: DB_COUNTRYLANG, Owner: SYSDBA */
CREATE TABLE DB_COUNTRYLANG (COUNTRY VARCHAR(6) NOT NULL,
        LANGUAGECD VARCHAR(6) NOT NULL,
        EFFDT DATE NOT NULL,
        EFFSTATUS VARCHAR(6),
        DESCR VARCHAR(64),
        DESCRLONG VARCHAR(256),
        LASTUPDATEDTTM TIMESTAMP,
        LASTUPDATEOPRID VARCHAR(20),
PRIMARY KEY (COUNTRY, LANGUAGECD, EFFDT));

/* Table: DB_CURRENCY, Owner: SYSDBA */
CREATE TABLE DB_CURRENCY (CURRENCYCD VARCHAR(6) NOT NULL,
        EFFDT DATE NOT NULL,
        EFFSTATUS VARCHAR(6),
        EXCHANGECURRENCYCD VARCHAR(6),
        EXCHANGERATE DOUBLE PRECISION,
        EXCHANGEBUNDLE INTEGER,
        DESCR VARCHAR(64),
        DESCRLONG VARCHAR(256),
        LASTUPDATEDTTM TIMESTAMP,
        LASTUPDATEOPRID VARCHAR(20),
PRIMARY KEY (CURRENCYCD, EFFDT));

/* Table: DB_DEPARTMENT_TBL, Owner: SYSDBA */
CREATE TABLE DB_DEPARTMENT_TBL (ORGID VARCHAR(20) NOT NULL,
        DEPTID VARCHAR(20) NOT NULL,
        EFFDT DATE NOT NULL,
        EFFSTATUS VARCHAR(6),
        FULLNAME VARCHAR(128),
        PERSID VARCHAR(20),
        DEPARTMENTCODE VARCHAR(32),
        DEPTIDPARENT VARCHAR(20),
        DESCR VARCHAR(64),
        DESCRLONG VARCHAR(256),
        LASTUPDATEDTTM TIMESTAMP,
        LASTUPDATEOPRID VARCHAR(20),
PRIMARY KEY (ORGID, DEPTID, EFFDT));

/* Table: DB_EMPLOYMENT_DT, Owner: SYSDBA */
CREATE TABLE DB_EMPLOYMENT_DT (ORGID VARCHAR(20) NOT NULL,
        PERSID VARCHAR(20) NOT NULL,
        EFFDT DATE NOT NULL,
        EFFSTATUS VARCHAR(6),
        FUNCTIONID VARCHAR(20),
        DEPTID VARCHAR(20),
        UNITID VARCHAR(20),
        LOCATIONID VARCHAR(20),
        BUILDINGID VARCHAR(20),
        ROOMID VARCHAR(20),
        LASTUPDATEDTTM TIMESTAMP,
        LASTUPDATEOPRID VARCHAR(20),
PRIMARY KEY (ORGID, PERSID, EFFDT));

/* Table: DB_ENROLLMENT_DT, Owner: SYSDBA */
CREATE TABLE DB_ENROLLMENT_DT (ORGID VARCHAR(20) NOT NULL,
        PERSID VARCHAR(20) NOT NULL,
        EFFDT DATE NOT NULL,
        EFFSTATUS VARCHAR(6),
        LASTUPDATEDTTM TIMESTAMP,
        LASTUPDATEOPRID VARCHAR(20),
PRIMARY KEY (ORGID, PERSID, EFFDT));

/* Table: DB_ETHNICITY, Owner: SYSDBA */
CREATE TABLE DB_ETHNICITY (ETHNICITY VARCHAR(6) NOT NULL,
        EFFDT DATE NOT NULL,
        EFFSTATUS VARCHAR(6),
        DESCR VARCHAR(64),
        DESCRLONG VARCHAR(256),
        LASTUPDATEDTTM TIMESTAMP,
        LASTUPDATEOPRID VARCHAR(20),
PRIMARY KEY (ETHNICITY, EFFDT));

/* Table: DB_ETHNICITYLANG, Owner: SYSDBA */
CREATE TABLE DB_ETHNICITYLANG (ETHNICITY VARCHAR(6) NOT NULL,
        LANGUAGECD VARCHAR(6) NOT NULL,
        EFFDT DATE NOT NULL,
        EFFSTATUS VARCHAR(6),
        DESCR VARCHAR(64),
        DESCRLONG VARCHAR(256),
        LASTUPDATEDTTM TIMESTAMP,
        LASTUPDATEOPRID VARCHAR(20),
PRIMARY KEY (ETHNICITY, LANGUAGECD, EFFDT));

/* Table: DB_FUNCTIONGROUP, Owner: SYSDBA */
CREATE TABLE DB_FUNCTIONGROUP (ORGID VARCHAR(20) NOT NULL,
        FUNCTIONGROUPID VARCHAR(20) NOT NULL,
        EFFDT DATE NOT NULL,
        EFFSTATUS VARCHAR(6),
        FULLNAME VARCHAR(128),
        DESCR VARCHAR(64),
        DESCRLONG VARCHAR(256),
        LASTUPDATEDTTM TIMESTAMP,
        LASTUPDATEOPRID VARCHAR(20),
PRIMARY KEY (ORGID, FUNCTIONGROUPID, EFFDT));

/* Table: DB_FUNCTION_TBL, Owner: SYSDBA */
CREATE TABLE DB_FUNCTION_TBL (ORGID VARCHAR(20) NOT NULL,
        FUNCTIONID VARCHAR(20) NOT NULL,
        EFFDT DATE NOT NULL,
        EFFSTATUS VARCHAR(6),
        FULLNAME VARCHAR(128),
        FUNCTIONCODE VARCHAR(32),
        DEPTID VARCHAR(20),
        UNITID VARCHAR(20),
        FUNCTIONGROUPID VARCHAR(20),
        DESCR VARCHAR(64),
        DESCRLONG VARCHAR(256),
        LASTUPDATEDTTM TIMESTAMP,
        LASTUPDATEOPRID VARCHAR(20),
PRIMARY KEY (ORGID, FUNCTIONID, EFFDT));

/* Table: DB_LOCATION_TBL, Owner: SYSDBA */
CREATE TABLE DB_LOCATION_TBL (ORGID VARCHAR(20) NOT NULL,
        LOCATIONID VARCHAR(20) NOT NULL,
        EFFDT DATE NOT NULL,
        EFFSTATUS VARCHAR(6),
        FULLNAME VARCHAR(128),
        LOCATIONCODE VARCHAR(32),
        PERSIDCONTACT VARCHAR(20),
        BUILDINGIDMAIN VARCHAR(20) NOT NULL,
        DESCR VARCHAR(64),
        DESCRLONG VARCHAR(256),
        LASTUPDATEDTTM TIMESTAMP,
        LASTUPDATEOPRID VARCHAR(20),
PRIMARY KEY (ORGID, LOCATIONID, EFFDT));

/* Table: DB_LOC_BLDG_DT, Owner: SYSDBA */
CREATE TABLE DB_LOC_BLDG_DT (ORGID VARCHAR(20) NOT NULL,
        LOCATIONID VARCHAR(20) NOT NULL,
        BUILDINGID VARCHAR(20) NOT NULL,
        EFFDT DATE NOT NULL,
        EFFSTATUS VARCHAR(6),
        LASTUPDATEDTTM TIMESTAMP,
        LASTUPDATEOPRID VARCHAR(20),
PRIMARY KEY (ORGID, LOCATIONID, BUILDINGID, EFFDT));

/* Table: DB_NAMEINFIX_LNG, Owner: SYSDBA */
CREATE TABLE DB_NAMEINFIX_LNG (NAMEINFIX VARCHAR(6) NOT NULL,
        LANGUAGECD VARCHAR(6) NOT NULL,
        EFFDT DATE NOT NULL,
        DESCR VARCHAR(64),
        DESCRLONG VARCHAR(256),
PRIMARY KEY (NAMEINFIX, LANGUAGECD, EFFDT));

/* Table: DB_NAMEINFIX_TBL, Owner: SYSDBA */
CREATE TABLE DB_NAMEINFIX_TBL (NAMEINFIX VARCHAR(6) NOT NULL,
        EFFDT DATE NOT NULL,
        EFFSTATUS VARCHAR(6),
        DESCR VARCHAR(64),
        DESCRLONG VARCHAR(256),
PRIMARY KEY (NAMEINFIX, EFFDT));

/* Table: DB_NAMEPOSTFIX_LNG, Owner: SYSDBA */
CREATE TABLE DB_NAMEPOSTFIX_LNG (NAMEPOSTFIX VARCHAR(6) NOT NULL,
        LANGUAGECD VARCHAR(6) NOT NULL,
        EFFDT DATE NOT NULL,
        DESCR VARCHAR(64),
        DESCRLONG VARCHAR(256),
PRIMARY KEY (NAMEPOSTFIX, LANGUAGECD, EFFDT));

/* Table: DB_NAMEPOSTFIX_TBL, Owner: SYSDBA */
CREATE TABLE DB_NAMEPOSTFIX_TBL (NAMEPOSTFIX VARCHAR(6) NOT NULL,
        EFFDT DATE NOT NULL,
        EFFSTATUS VARCHAR(6),
        DESCR VARCHAR(64),
        DESCRLONG VARCHAR(256),
PRIMARY KEY (NAMEPOSTFIX, EFFDT));

/* Table: DB_NAMEPREFIX_LNG, Owner: SYSDBA */
CREATE TABLE DB_NAMEPREFIX_LNG (NAMEPREFIX VARCHAR(6) NOT NULL,
        LANGUAGECD VARCHAR(6) NOT NULL,
        EFFDT DATE NOT NULL,
        DESCR VARCHAR(64),
        DESCRLONG VARCHAR(256),
PRIMARY KEY (NAMEPREFIX, LANGUAGECD, EFFDT));

/* Table: DB_NAMEPREFIX_TBL, Owner: SYSDBA */
CREATE TABLE DB_NAMEPREFIX_TBL (NAMEPREFIX VARCHAR(6) NOT NULL,
        EFFDT DATE NOT NULL,
        EFFSTATUS VARCHAR(6),
        DESCR VARCHAR(64),
        DESCRLONG VARCHAR(256),
PRIMARY KEY (NAMEPREFIX, EFFDT));

/* Table: DB_NATIONALITY, Owner: SYSDBA */
CREATE TABLE DB_NATIONALITY (NATIONALITY VARCHAR(6) NOT NULL,
        EFFDT DATE NOT NULL,
        EFFSTATUS VARCHAR(6),
        DESCR VARCHAR(64),
        DESCRLONG VARCHAR(256),
        LASTUPDATEDTTM TIMESTAMP,
        LASTUPDATEOPRID VARCHAR(20),
PRIMARY KEY (NATIONALITY, EFFDT));

/* Table: DB_NATIONALITYLANG, Owner: SYSDBA */
CREATE TABLE DB_NATIONALITYLANG (NATIONALITY VARCHAR(6) NOT NULL,
        LANGUAGECD VARCHAR(6) NOT NULL,
        EFFDT DATE NOT NULL,
        EFFSTATUS VARCHAR(6),
        DESCR VARCHAR(64),
        DESCRLONG VARCHAR(256),
        LASTUPDATEDTTM TIMESTAMP,
        LASTUPDATEOPRID VARCHAR(20),
PRIMARY KEY (NATIONALITY, LANGUAGECD, EFFDT));

/* Table: DB_ORGANIZATION_TBL, Owner: SYSDBA */
CREATE TABLE DB_ORGANIZATION_TBL (ORGID VARCHAR(20) NOT NULL,
        EFFDT DATE NOT NULL,
        EFFSTATUS VARCHAR(6),
        FULLNAME VARCHAR(128),
        ORGCODE VARCHAR(32),
        LOCATIONIDMAIN VARCHAR(20),
        PERSIDCONTACT VARCHAR(20),
        DESCR VARCHAR(64),
        DESCRLONG VARCHAR(256),
        LASTUPDATEDTTM TIMESTAMP,
        LASTUPDATEOPRID VARCHAR(20),
PRIMARY KEY (ORGID, EFFDT));

/* Table: DB_ORG_TYPE, Owner: SYSDBA */
CREATE TABLE DB_ORG_TYPE (ORGID VARCHAR(20) NOT NULL,
        ORGTYPE VARCHAR(6) NOT NULL,
        EFFDT DATE NOT NULL,
        EFFSTATUS VARCHAR(6),
        ORGCODE VARCHAR(32),
        DESCR VARCHAR(64),
        DESCRLONG VARCHAR(256),
        LASTUPDATEDTTM TIMESTAMP,
        LASTUPDATEOPRID VARCHAR(20),
PRIMARY KEY (ORGID, ORGTYPE, EFFDT));

/* Table: DB_PERSADDRESS_DT, Owner: SYSDBA */
CREATE TABLE DB_PERSADDRESS_DT (PERSID VARCHAR(20) NOT NULL,
        ADDRESSTYPE VARCHAR(6) NOT NULL,
        EFFDT DATE NOT NULL,
        EFFSTATUS VARCHAR(6),
        COUNTRY VARCHAR(6),
        REGION VARCHAR(64),
        CITY VARCHAR(64),
        STREET VARCHAR(64),
        NR1 VARCHAR(12),
        NR2 VARCHAR(12),
        POSTAL VARCHAR(12),
        DESCR VARCHAR(64),
        DESCRLONG VARCHAR(256),
        LASTUPDATEDTTM TIMESTAMP,
        LASTUPDATEOPRID VARCHAR(20),
PRIMARY KEY (PERSID, ADDRESSTYPE, EFFDT));

/* Table: DB_PERSEMAIL_DT, Owner: SYSDBA */
CREATE TABLE DB_PERSEMAIL_DT (PERSID VARCHAR(20) NOT NULL,
        EMAILTYPE VARCHAR(6) NOT NULL,
        EFFDT DATE NOT NULL,
        EFFSTATUS VARCHAR(6),
        EMAILADDRESS VARCHAR(64),
        DESCR VARCHAR(64),
        DESCRLONG VARCHAR(256),
        LASTUPDATEDTTM TIMESTAMP,
        LASTUPDATEOPRID VARCHAR(20),
PRIMARY KEY (PERSID, EMAILTYPE, EFFDT));

/* Table: DB_PERSEXTERNALID_DT, Owner: SYSDBA */
CREATE TABLE DB_PERSEXTERNALID_DT (PERSID VARCHAR(20) NOT NULL,
        EXTERNALDATATYPE VARCHAR(6) NOT NULL,
        EFFDT DATE NOT NULL,
        EFFSTATUS VARCHAR(6),
        EXTERNALID VARCHAR(64),
        DESCR VARCHAR(64),
        DESCRLONG VARCHAR(256),
        LASTUPDATEDTTM TIMESTAMP,
        LASTUPDATEOPRID VARCHAR(20),
PRIMARY KEY (PERSID, EXTERNALDATATYPE, EFFDT));

/* Table: DB_PERSNAME_DT, Owner: SYSDBA */
CREATE TABLE DB_PERSNAME_DT (PERSID VARCHAR(20) NOT NULL,
        NAMETYPE VARCHAR(6) NOT NULL,
        EFFDT DATE NOT NULL,
        EFFSTATUS VARCHAR(6),
        TITLE VARCHAR(6),
        NAMEPREFIX VARCHAR(6),
        INITIALS VARCHAR(12),
        FIRSTNAME VARCHAR(64),
        CALLINGNAME VARCHAR(64),
        MIDDLENAME VARCHAR(64),
        NAMEINFIX VARCHAR(6),
        LASTNAME VARCHAR(64),
        NAMEPOSTFIX VARCHAR(6),
        FULLNAME VARCHAR(128),
        LASTUPDATEDTTM TIMESTAMP,
        LASTUPDATEOPRID VARCHAR(20),
PRIMARY KEY (PERSID, NAMETYPE, EFFDT));

/* Table: DB_PERSON_TBL, Owner: SYSDBA */
CREATE TABLE DB_PERSON_TBL (PERSID VARCHAR(20) NOT NULL,
        EFFDT DATE NOT NULL,
        GENDER VARCHAR(6) NOT NULL,
        NATIONALITY VARCHAR(6),
        ETHNICITY VARCHAR(6),
        BIRTHDATE DATE,
        BIRTHTIME TIME,
        BIRTHCOUNTRY VARCHAR(6),
        BIRTHCITY VARCHAR(64),
        DECEASEDATE DATE,
        MARITALSTATE VARCHAR(6),
        ADDRESSTYPE VARCHAR(6),
        EMAILTYPE VARCHAR(6),
        NAMETYPE VARCHAR(6),
        PHONETYPE VARCHAR(6),
        LASTUPDATEDTTM TIMESTAMP,
        LASTUPDATEOPRID VARCHAR(20),
PRIMARY KEY (PERSID, EFFDT));

/* Table: DB_PERSPHONE_DT, Owner: SYSDBA */
CREATE TABLE DB_PERSPHONE_DT (PERSID VARCHAR(20) NOT NULL,
        PHONETYPE VARCHAR(6) NOT NULL,
        EFFDT DATE NOT NULL,
        EFFSTATUS VARCHAR(6),
        COUNTRY VARCHAR(6),
        PHONENUMBER VARCHAR(32),
        EXTENTIONNUMBER VARCHAR(12),
        DESCR VARCHAR(64),
        DESCRLONG VARCHAR(256),
        LASTUPDATEDTTM TIMESTAMP,
        LASTUPDATEOPRID VARCHAR(20),
PRIMARY KEY (PERSID, PHONETYPE, EFFDT));

/* Table: DB_POSTAL_REF, Owner: SYSDBA */
CREATE TABLE DB_POSTAL_REF (COUNTRY VARCHAR(6) NOT NULL,
        POSTAL VARCHAR(12) NOT NULL,
        POSTALRANGE VARCHAR(6) NOT NULL,
        POSTAL_BRKPNT_FROM VARCHAR(12) NOT NULL,
        POSTAL_BRKPNT_UNTIL VARCHAR(12),
        REGION VARCHAR(64),
        CITY VARCHAR(64),
        STREET VARCHAR(64),
        DESCR VARCHAR(64),
        DESCRLONG VARCHAR(256),
        LASTUPDATEDTTM TIMESTAMP,
        LASTUPDATEOPRID VARCHAR(20),
PRIMARY KEY (COUNTRY, POSTAL, POSTALRANGE, POSTAL_BRKPNT_FROM));

/* Table: DB_REGION, Owner: SYSDBA */
CREATE TABLE DB_REGION (COUNTRY VARCHAR(6) NOT NULL,
        REGION VARCHAR(64) NOT NULL,
        EFFDT DATE NOT NULL,
        EFFSTATUS VARCHAR(6),
        DESCR VARCHAR(64),
        DESCRLONG VARCHAR(256),
        LASTUPDATEDTTM TIMESTAMP,
        LASTUPDATEOPRID VARCHAR(20),
PRIMARY KEY (COUNTRY, REGION, EFFDT));

/* Table: DB_RELATIONSHIP_DT, Owner: SYSDBA */
CREATE TABLE DB_RELATIONSHIP_DT (PERSID VARCHAR(20) NOT NULL,
        RELATIONTYPE VARCHAR(6) NOT NULL,
        EFFDT DATE NOT NULL,
        EFFSTATUS VARCHAR(6),
        PERSIDRELATION VARCHAR(20),
        FULLNAME VARCHAR(128),
        LASTUPDATEDTTM TIMESTAMP,
        LASTUPDATEOPRID VARCHAR(20),
PRIMARY KEY (PERSID, RELATIONTYPE, EFFDT));

/* Table: DB_ROOM_TBL, Owner: SYSDBA */
CREATE TABLE DB_ROOM_TBL (BUILDINGID VARCHAR(20) NOT NULL,
        ROOMID VARCHAR(20) NOT NULL,
        EFFDT DATE NOT NULL,
        EFFSTATUS VARCHAR(6),
        FLOOR INTEGER,
        WING VARCHAR(12),
        ROOM VARCHAR(12),
PRIMARY KEY (BUILDINGID, ROOMID, EFFDT));

/* Table: DB_UNIT_TBL, Owner: SYSDBA */
CREATE TABLE DB_UNIT_TBL (ORGID VARCHAR(20) NOT NULL,
        UNITID VARCHAR(20) NOT NULL,
        EFFDT DATE NOT NULL,
        EFFSTATUS VARCHAR(6),
        FULLNAME VARCHAR(128),
        UNITCODE VARCHAR(32),
        PERSID VARCHAR(20),
        UNITIDPARENT VARCHAR(20),
        DESCR VARCHAR(64),
        DESCRLONG VARCHAR(256),
        LASTUPDATEDTTM TIMESTAMP,
        LASTUPDATEOPRID VARCHAR(20),
PRIMARY KEY (ORGID, UNITID, EFFDT));

/* Table: SYS_ACCESS, Owner: SYSDBA */
CREATE TABLE SYS_ACCESS (ACCESSID VARCHAR(20) NOT NULL,
        ACCESSAUTHTYPE VARCHAR(6) NOT NULL,
        ACCESSAUTH VARCHAR(32),
PRIMARY KEY (ACCESSID));

/* Table: SYS_ACTION, Owner: SYSDBA */
CREATE TABLE SYS_ACTION (ACTIONID VARCHAR(20) NOT NULL,
        SCHEDULEID VARCHAR(20) NOT NULL,
        EFFDT DATE NOT NULL,
        EFFSTATUS VARCHAR(6),
        DESCR VARCHAR(64),
        DESCRLONG VARCHAR(256),
        LASTUPDATEDTTM TIMESTAMP,
        LASTUPDATEOPRID VARCHAR(20),
PRIMARY KEY (ACTIONID, SCHEDULEID, EFFDT));

/* Table: SYS_ACTIONITEM, Owner: SYSDBA */
CREATE TABLE SYS_ACTIONITEM (ACTIONID VARCHAR(20) NOT NULL,
        SEQUENCENUMBER INTEGER NOT NULL,
        CONID VARCHAR(20),
        SQLACTIONID VARCHAR(20),
PRIMARY KEY (ACTIONID, SEQUENCENUMBER));

/* Table: SYS_CONFIGBASE, Owner: SYSDBA */
CREATE TABLE SYS_CONFIGBASE (LANGUAGECD VARCHAR(6),
        CURRENCYCD VARCHAR(6),
        APPNAME VARCHAR(128),
        APPVERSION VARCHAR(20));

/* Table: SYS_CONNECTION, Owner: SYSDBA */
CREATE TABLE SYS_CONNECTION (CONID VARCHAR(20) NOT NULL,
        CONTYPE VARCHAR(6),
        CONSOURCE VARCHAR(128),
        CONLOGIN VARCHAR(20),
        CONAUTH VARCHAR(64),
        DESCR VARCHAR(64),
        DESCRLONG VARCHAR(256),
        LASTUPDATEDTTM TIMESTAMP,
        LASTUPDATEOPRID VARCHAR(20),
PRIMARY KEY (CONID));

/* Table: SYS_CONNECTIONSQL, Owner: SYSDBA */
CREATE TABLE SYS_CONNECTIONSQL (CONID VARCHAR(20) NOT NULL,
        SQLACTIONID VARCHAR(20) NOT NULL,
        SQLSTATEMENT VARCHAR(256),
PRIMARY KEY (CONID, SQLACTIONID));

/* Table: SYS_FIELD, Owner: SYSDBA */
CREATE TABLE SYS_FIELD (FIELDNAME VARCHAR(20) NOT NULL,
        VERSIONNUMBER INTEGER NOT NULL,
        FIELDTYPE VARCHAR(6) NOT NULL,
        FIELDLENGTH INTEGER NOT NULL,
        FIELDPRECISION INTEGER NOT NULL,
        DESCRSHORT VARCHAR(12),
        DESCR VARCHAR(64),
        DESCRLONG VARCHAR(256),
        X_LOOKUPTYPE VARCHAR(6),
        X_LOOKUPRECORD VARCHAR(20),
        X_LOOKUPFIELD VARCHAR(20),
        LASTUPDATEDTTM TIMESTAMP,
        LASTUPDATEOPRID VARCHAR(20),
PRIMARY KEY (FIELDNAME));

/* Table: SYS_FIELDLANG, Owner: SYSDBA */
CREATE TABLE SYS_FIELDLANG (FIELDNAME VARCHAR(20) NOT NULL,
        LANGUAGECD VARCHAR(6) NOT NULL,
        DESCRSHORT VARCHAR(12),
        DESCR VARCHAR(64),
        DESCRLONG VARCHAR(256),
        LASTUPDATEDTTM TIMESTAMP,
        LASTUPDATEOPRID VARCHAR(20),
PRIMARY KEY (FIELDNAME, LANGUAGECD));

/* Table: SYS_FIELDVALUE, Owner: SYSDBA */
CREATE TABLE SYS_FIELDVALUE (FIELDNAME VARCHAR(20) NOT NULL,
        FIELDVALUE VARCHAR(6) NOT NULL,
        EFFDT DATE NOT NULL,
        EFFSTATUS VARCHAR(6),
        DESCRSHORT VARCHAR(12),
        DESCR VARCHAR(64),
        DESCRLONG VARCHAR(256),
        LASTUPDATEDTTM TIMESTAMP,
        LASTUPDATEOPRID VARCHAR(20),
PRIMARY KEY (FIELDNAME, FIELDVALUE, EFFDT));

/* Table: SYS_FIELDVALUELANG, Owner: SYSDBA */
CREATE TABLE SYS_FIELDVALUELANG (FIELDNAME VARCHAR(20) NOT NULL,
        FIELDVALUE VARCHAR(6) NOT NULL,
        LANGUAGECD VARCHAR(6) NOT NULL,
        EFFDT DATE NOT NULL,
        EFFSTATUS VARCHAR(6),
        DESCRSHORT VARCHAR(12),
        DESCR VARCHAR(64),
        DESCRLONG VARCHAR(256),
        LASTUPDATEDTTM TIMESTAMP,
        LASTUPDATEOPRID VARCHAR(20),
PRIMARY KEY (FIELDNAME, FIELDVALUE, LANGUAGECD, EFFDT));

/* Table: SYS_GENERATEDID, Owner: SYSDBA */
CREATE TABLE SYS_GENERATEDID (IDNAME VARCHAR(20) NOT NULL,
        IDMAXSIZE INTEGER NOT NULL,
        IDDEFAULTSIZE INTEGER,
        IDLASTVALUE INTEGER,
PRIMARY KEY (IDNAME));

/* Table: SYS_LANGUAGE, Owner: SYSDBA */
CREATE TABLE SYS_LANGUAGE (LANGUAGECD VARCHAR(6) NOT NULL,
        EFFDT DATE NOT NULL,
        EFFSTATUS VARCHAR(6),
        DESCRSHORT VARCHAR(12),
        DESCR VARCHAR(64),
        DESCRLONG VARCHAR(256),
        LASTUPDATEDTTM TIMESTAMP,
        LASTUPDATEOPRID VARCHAR(20),
PRIMARY KEY (LANGUAGECD, EFFDT));

/* Table: SYS_OPERATOR, Owner: SYSDBA */
CREATE TABLE SYS_OPERATOR (OPRID VARCHAR(20) NOT NULL,
        OPRTYPE VARCHAR(6) NOT NULL,
        PERSID VARCHAR(20),
        FULLNAME VARCHAR(128),
        OPRAUTHTYPE VARCHAR(6) NOT NULL,
        OPRAUTH VARCHAR(32),
        ACCESSID VARCHAR(20) NOT NULL,
        OPRPREF VARCHAR(20),
        DESCR VARCHAR(64),
        DESCRLONG VARCHAR(256),
        LASTUPDATEDTTM TIMESTAMP,
        LASTUPDATEOPRID VARCHAR(20),
PRIMARY KEY (OPRID, OPRTYPE));

/* Table: SYS_OPRPAGEACCESS, Owner: SYSDBA */
CREATE TABLE SYS_OPRPAGEACCESS (OPRID VARCHAR(20) NOT NULL,
        PAGENAME VARCHAR(20) NOT NULL,
        ACCESSTYPE VARCHAR(6) NOT NULL,
        LASTUPDATEDTTM TIMESTAMP,
        LASTUPDATEOPRID VARCHAR(20),
PRIMARY KEY (OPRID, PAGENAME));

/* Table: SYS_OPRRECORDACCESS, Owner: SYSDBA */
CREATE TABLE SYS_OPRRECORDACCESS (OPRID VARCHAR(20) NOT NULL,
        RECORDNAME VARCHAR(20) NOT NULL,
        ACCESSTYPE VARCHAR(6) NOT NULL,
        LASTUPDATEDTTM TIMESTAMP,
        LASTUPDATEOPRID VARCHAR(20),
PRIMARY KEY (OPRID, RECORDNAME));

/* Table: SYS_RECORD, Owner: SYSDBA */
CREATE TABLE SYS_RECORD (RECORDNAME VARCHAR(20) NOT NULL,
        VERSIONNUMBER INTEGER NOT NULL,
        RECORDTYPE VARCHAR(6) NOT NULL,
        RECORDPARENT VARCHAR(20),
        RECORDSEARCH VARCHAR(20),
        RECORDSECURITY VARCHAR(20),
        X_TABLENAME VARCHAR(20),
        DESCRSHORT VARCHAR(12),
        DESCR VARCHAR(64),
        DESCRLONG VARCHAR(256),
        LASTUPDATEDTTM TIMESTAMP,
        LASTUPDATEOPRID VARCHAR(20),
PRIMARY KEY (RECORDNAME));

/* Table: SYS_RECORDFIELD, Owner: SYSDBA */
CREATE TABLE SYS_RECORDFIELD (RECORDNAME VARCHAR(20) NOT NULL,
        FIELDNAME VARCHAR(20) NOT NULL,
        SEQUENCENUMBER INTEGER NOT NULL,
        VERSIONNUMBER INTEGER,
        KEYFIELD VARCHAR(6),
        SEARCHFIELD VARCHAR(6),
        ALTSEARCHFIELD VARCHAR(6),
        LISTBOXFIELD VARCHAR(6),
        REQUIREDFIELD VARCHAR(6),
        DEFAULTVALUE VARCHAR(20),
        X_LOOKUPTYPE VARCHAR(6),
        X_LOOKUPRECORD VARCHAR(20),
        X_LOOKUPFIELD VARCHAR(20),
        LASTUPDATEDTTM TIMESTAMP,
        LASTUPDATEOPRID VARCHAR(20),
PRIMARY KEY (RECORDNAME, FIELDNAME));

/* Table: SYS_RECORDLANG, Owner: SYSDBA */
CREATE TABLE SYS_RECORDLANG (RECORDNAME VARCHAR(20) NOT NULL,
        LANGUAGECD VARCHAR(6) NOT NULL,
        DESCRSHORT VARCHAR(12),
        DESCR VARCHAR(64),
        DESCRLONG VARCHAR(256),
        LASTUPDATEDTTM TIMESTAMP,
        LASTUPDATEOPRID VARCHAR(20),
PRIMARY KEY (RECORDNAME, LANGUAGECD));

/* Table: SYS_SCHEDULE, Owner: SYSDBA */
CREATE TABLE SYS_SCHEDULE (SCHEDULEID VARCHAR(20) NOT NULL,
        SCHEDULETYPE VARCHAR(6),
        SCHEDULEDATE DATE,
        SCHEDULETIME TIME,
        SCHEDULEDAY VARCHAR(6),
        SCHEDULEWEEK VARCHAR(6),
        SCHEDULEMONTH VARCHAR(6),
        SCHEDULEYEAR VARCHAR(6),
PRIMARY KEY (SCHEDULEID));

