USE SA76SY2
GO
SELECT RTRIM(db_name(db_id())) AS DATABASE_NAME
GO
--SELECT SO.NAME, SO.TYPE, SC.* FROM SYSOBJECTS SO JOIN SYSCOLUMNS SC ON (SO.ID = SC.ID AND SO.TYPE = 'U')
--  WHERE SC.NAME LIKE 'ADMIT_TYPE'
--GO

--    
-- WARNING: 
--    
-- This script should not be run in Data Mover.  It may contain platform 
-- specific syntax that Data Mover is unable to comprehend.  Please use the 
-- SQL query tool included with your database engine to process this script. 
--    
SET IMPLICIT_TRANSACTIONS ON
GO
IF EXISTS (SELECT 'X' FROM SYSOBJECTS WHERE TYPE = 'U' AND NAME =
 'PST_PNLFIELDS') DROP TABLE PST_PNLFIELDS
GO
CREATE TABLE PST_PNLFIELDS (SRC_TGT CHAR(1) NOT NULL,
   FIELDNUM SMALLINT NOT NULL,
   FIELDTYPE SMALLINT NOT NULL,
   EDITSIZE SMALLINT NOT NULL,
   DSPLFORMAT INT NOT NULL,
   FIELDLEFT SMALLINT NOT NULL,
   FIELDTOP SMALLINT NOT NULL,
   FIELDRIGHT SMALLINT NOT NULL,
   FIELDBOTTOM SMALLINT NOT NULL,
   EDITLBLLEFT SMALLINT NOT NULL,
   EDITLBLTOP SMALLINT NOT NULL,
   EDITLBLRIGHT SMALLINT NOT NULL,
   EDITLBLBOTTOM SMALLINT NOT NULL,
   DSPLFILL CHAR(1) NOT NULL,
   LBLTYPE SMALLINT NOT NULL,
   LBLLOC SMALLINT NOT NULL,
   LBLPADSIZE SMALLINT NOT NULL,
   LBLTEXT CHAR(60) NOT NULL,
   FIELDUSE SMALLINT NOT NULL,
   OCCURSLEVEL SMALLINT NOT NULL,
   RECNAME CHAR(15) NOT NULL,
   FIELDNAME CHAR(18) NOT NULL,
   ONVALUE CHAR(4) NOT NULL,
   OFFVALUE CHAR(4) NOT NULL,
   ASSOCFIELDNUM SMALLINT NOT NULL,
   OCCURSCOUNT1 SMALLINT NOT NULL,
   OCCURSOFFSET1 SMALLINT NOT NULL,
   OCCURSCOUNT2 SMALLINT NOT NULL,
   OCCURSOFFSET2 SMALLINT NOT NULL,
   OCCURSCOUNT3 SMALLINT NOT NULL,
   OCCURSOFFSET3 SMALLINT NOT NULL,
   HELPCONTEXTNUM INT NOT NULL,
   SUBPNLNAME CHAR(18) NOT NULL,
   SUBPNLVER INT NOT NULL,
   FIELDSTYLE CHAR(30) NOT NULL,
   LABELSTYLE CHAR(30) NOT NULL,
   FIELDSIZETYPE SMALLINT NOT NULL,
   LABELSIZETYPE SMALLINT NOT NULL,
   IMAGE_FMT SMALLINT NOT NULL,
   PRCSTYPE CHAR(30) NOT NULL,
   PRCSNAME CHAR(8) NOT NULL,
   PROMPTFIELD CHAR(18) NOT NULL,
   FORMATFAMILY CHAR(15) NOT NULL,
   DISPFMTNAME CHAR(15) NOT NULL,
   POPUPMENU CHAR(30) NOT NULL,
   TREECTRLID SMALLINT NOT NULL,
   TREECTRLTYPE SMALLINT NOT NULL,
   MULTIRECTREE SMALLINT NOT NULL,
   NODECOUNT SMALLINT NOT NULL,
   GRDCOLUMNCOUNT SMALLINT NOT NULL,
   GRDSHOWCOLHDG SMALLINT NOT NULL,
   GRDSHOWROWHDG SMALLINT NOT NULL,
   GRDCOLHDGSTYLE CHAR(30) NOT NULL,
   GRDODDROWSTYLE CHAR(30) NOT NULL,
   GRDEVENROWSTYLE CHAR(30) NOT NULL,
   GRDLBLMSGSET SMALLINT NOT NULL,
   GRDLBLMSGNUM SMALLINT NOT NULL,
   GRDLBLALIGN SMALLINT NOT NULL,
   GRDACTTYPE SMALLINT NOT NULL,
   GRDACTRECNAME CHAR(15) NOT NULL,
   GRDACTFIELDNAME CHAR(18) NOT NULL,
   GRDACTPNLNAME CHAR(18) NOT NULL)
GO
COMMIT
GO
CREATE NONCLUSTERED INDEX PSAPST_PNLFIELDS ON PST_PNLFIELDS (FIELDTYPE
,
   RECNAME,
   FIELDNAME,
   ONVALUE,
   SRC_TGT,
   LBLTEXT)
GO
COMMIT
GO


--SELECT * FROM PST_PNLFIELDS
--TRUNCATE TABLE PST_PNLFIELDS
--  DELETE FROM PST_PNLFIELDS
--SELECT * FROM sysindexes WHERE name LIKE '%KPP%'
--DROP INDEX PST_PNLFIELDS.AC_KPP_PST_PNLFLD
--CREATE INDEX AC_KPP_PST_PNLFLD ON PST_PNLFIELDS(TREECTRLID, FIELDNUM, FIELDTYPE)
-- BACKUP LOG SA76SY2 WITH TRUNCATE_ONLY
--GO

SELECT 
A.SRC_TGT             ,
A.FIELDNUM            ,
A.FIELDTYPE           ,
A.EDITSIZE            ,
A.DSPLFORMAT          ,
A.FIELDLEFT           ,
A.FIELDTOP            ,
A.FIELDRIGHT          ,
A.FIELDBOTTOM         ,
A.EDITLBLLEFT         ,
A.EDITLBLTOP          ,
A.EDITLBLRIGHT        ,
A.EDITLBLBOTTOM       ,
A.DSPLFILL            ,
A.LBLTYPE             ,
A.LBLLOC              ,
A.LBLPADSIZE          ,
A.LBLTEXT             ,
A.FIELDUSE            ,
A.OCCURSLEVEL         ,
A.RECNAME             ,
A.FIELDNAME           ,
A.ONVALUE             ,
A.OFFVALUE            ,
A.ASSOCFIELDNUM       ,
A.OCCURSCOUNT1        ,
A.OCCURSOFFSET1       ,
A.OCCURSCOUNT2        ,
A.OCCURSOFFSET2       ,
A.OCCURSCOUNT3        ,
A.OCCURSOFFSET3       ,
A.HELPCONTEXTNUM      ,
A.SUBPNLNAME          ,
A.SUBPNLVER           ,
A.FIELDSTYLE          ,
A.LABELSTYLE          ,
A.FIELDSIZETYPE       ,
A.LABELSIZETYPE       ,
A.IMAGE_FMT           ,
A.PRCSTYPE            ,
A.PRCSNAME            ,
A.PROMPTFIELD         ,
A.FORMATFAMILY        ,
A.DISPFMTNAME         ,
A.POPUPMENU           ,
A.TREECTRLID          ,
A.TREECTRLTYPE        ,
A.MULTIRECTREE        ,
A.NODECOUNT           ,
A.GRDCOLUMNCOUNT      ,
A.GRDSHOWCOLHDG       ,
A.GRDSHOWROWHDG       ,
A.GRDCOLHDGSTYLE      ,
A.GRDODDROWSTYLE      ,
A.GRDEVENROWSTYLE     ,
A.GRDLBLMSGSET        ,
A.GRDLBLMSGNUM        ,
A.GRDLBLALIGN         ,
A.GRDACTTYPE          ,
A.GRDACTRECNAME       ,
A.GRDACTFIELDNAME     ,
A.GRDACTPNLNAME       

FROM PST_PNLFIELDS A, PST_PNLFIELDS C WHERE 
(C.TREECTRLID > 0 AND A.TREECTRLID > 0
AND C.FIELDNUM = A.FIELDNUM
AND C.FIELDTYPE = A.FIELDTYPE
AND C.EDITSIZE = A.EDITSIZE
AND C.DSPLFORMAT = A.DSPLFORMAT
AND C.FIELDLEFT = A.FIELDLEFT
AND C.FIELDTOP = A.FIELDTOP
AND C.FIELDRIGHT = A.FIELDRIGHT
AND C.FIELDBOTTOM = A.FIELDBOTTOM
AND C.EDITLBLLEFT = A.EDITLBLLEFT
AND C.EDITLBLTOP = A.EDITLBLTOP
AND C.EDITLBLRIGHT = A.EDITLBLRIGHT
AND C.EDITLBLBOTTOM = A.EDITLBLBOTTOM
AND C.DSPLFILL = A.DSPLFILL
AND C.LBLTYPE = A.LBLTYPE
AND C.LBLLOC = A.LBLLOC
AND C.LBLPADSIZE = A.LBLPADSIZE
AND C.LBLTEXT = A.LBLTEXT
AND C.FIELDUSE = A.FIELDUSE
AND C.OCCURSLEVEL = A.OCCURSLEVEL
AND C.RECNAME = A.RECNAME
AND C.FIELDNAME = A.FIELDNAME
AND C.ONVALUE = A.ONVALUE
AND C.OFFVALUE = A.OFFVALUE
AND C.ASSOCFIELDNUM = A.ASSOCFIELDNUM
AND C.OCCURSCOUNT1 = A.OCCURSCOUNT1
AND C.OCCURSOFFSET1 = A.OCCURSOFFSET1
AND C.OCCURSCOUNT2 = A.OCCURSCOUNT2
AND C.OCCURSOFFSET2 = A.OCCURSOFFSET2
AND C.OCCURSCOUNT3 = A.OCCURSCOUNT3
AND C.OCCURSOFFSET3 = A.OCCURSOFFSET3
AND C.HELPCONTEXTNUM= A.HELPCONTEXTNUM
AND C.SUBPNLNAME = A.SUBPNLNAME
AND C.SUBPNLVER = A.SUBPNLVER
AND C.FIELDSTYLE = A.FIELDSTYLE
AND C.LABELSTYLE = A.LABELSTYLE
AND C.FIELDSIZETYPE = A.FIELDSIZETYPE
AND C.LABELSIZETYPE = A.LABELSIZETYPE
AND C.IMAGE_FMT = A.IMAGE_FMT
AND C.PRCSTYPE = A.PRCSTYPE
AND C.PRCSNAME = A.PRCSNAME
AND C.PROMPTFIELD = A.PROMPTFIELD
AND C.FORMATFAMILY = A.FORMATFAMILY
AND C.DISPFMTNAME = A.DISPFMTNAME
AND C.POPUPMENU = A.POPUPMENU
AND C.TREECTRLTYPE = A.TREECTRLTYPE
AND C.MULTIRECTREE = A.MULTIRECTREE
AND C.NODECOUNT = A.NODECOUNT
AND C.GRDCOLUMNCOUNT = A.GRDCOLUMNCOUNT
AND C.GRDSHOWCOLHDG = A.GRDSHOWCOLHDG
AND C.GRDSHOWROWHDG = A.GRDSHOWROWHDG
AND C.GRDCOLHDGSTYLE = A.GRDCOLHDGSTYLE
AND C.GRDODDROWSTYLE = A.GRDODDROWSTYLE
AND C.GRDEVENROWSTYLE= A.GRDEVENROWSTYLE
AND C.GRDLBLMSGSET = A.GRDLBLMSGSET
AND C.GRDLBLMSGNUM = A.GRDLBLMSGNUM
AND C.GRDLBLALIGN = A.GRDLBLALIGN
AND C.GRDACTTYPE = A.GRDACTTYPE
AND C.GRDACTRECNAME = A.GRDACTRECNAME
AND C.GRDACTFIELDNAME= A.GRDACTFIELDNAME
AND C.GRDACTPNLNAME = A.GRDACTPNLNAME
AND C.SRC_TGT <> A.SRC_TGT)
OR
NOT EXISTS (SELECT 'X' FROM PST_PNLFIELDS B WHERE
    B.FIELDNUM = A.FIELDNUM
AND B.FIELDTYPE = A.FIELDTYPE
AND B.EDITSIZE = A.EDITSIZE
AND B.DSPLFORMAT = A.DSPLFORMAT
AND B.FIELDLEFT = A.FIELDLEFT
AND B.FIELDTOP = A.FIELDTOP
AND B.FIELDRIGHT = A.FIELDRIGHT
AND B.FIELDBOTTOM = A.FIELDBOTTOM
AND B.EDITLBLLEFT = A.EDITLBLLEFT
AND B.EDITLBLTOP = A.EDITLBLTOP
AND B.EDITLBLRIGHT = A.EDITLBLRIGHT
AND B.EDITLBLBOTTOM = A.EDITLBLBOTTOM
AND B.DSPLFILL = A.DSPLFILL
AND B.LBLTYPE = A.LBLTYPE
AND B.LBLLOC = A.LBLLOC
AND B.LBLPADSIZE = A.LBLPADSIZE
AND B.LBLTEXT = A.LBLTEXT
AND B.FIELDUSE = A.FIELDUSE
AND B.OCCURSLEVEL = A.OCCURSLEVEL
AND B.RECNAME = A.RECNAME
AND B.FIELDNAME = A.FIELDNAME
AND B.ONVALUE = A.ONVALUE
AND B.OFFVALUE = A.OFFVALUE
AND B.ASSOCFIELDNUM = A.ASSOCFIELDNUM
AND B.OCCURSCOUNT1 = A.OCCURSCOUNT1
AND B.OCCURSOFFSET1 = A.OCCURSOFFSET1
AND B.OCCURSCOUNT2 = A.OCCURSCOUNT2
AND B.OCCURSOFFSET2 = A.OCCURSOFFSET2
AND B.OCCURSCOUNT3 = A.OCCURSCOUNT3
AND B.OCCURSOFFSET3 = A.OCCURSOFFSET3
AND B.HELPCONTEXTNUM= A.HELPCONTEXTNUM
AND B.SUBPNLNAME = A.SUBPNLNAME
AND B.SUBPNLVER = A.SUBPNLVER
AND B.FIELDSTYLE = A.FIELDSTYLE
AND B.LABELSTYLE = A.LABELSTYLE
AND B.FIELDSIZETYPE = A.FIELDSIZETYPE
AND B.LABELSIZETYPE = A.LABELSIZETYPE
AND B.IMAGE_FMT = A.IMAGE_FMT
AND B.PRCSTYPE = A.PRCSTYPE
AND B.PRCSNAME = A.PRCSNAME
AND B.PROMPTFIELD = A.PROMPTFIELD
AND B.FORMATFAMILY = A.FORMATFAMILY
AND B.DISPFMTNAME = A.DISPFMTNAME
AND B.POPUPMENU = A.POPUPMENU
AND B.TREECTRLID = A.TREECTRLID
AND B.TREECTRLTYPE = A.TREECTRLTYPE
AND B.MULTIRECTREE = A.MULTIRECTREE
AND B.NODECOUNT = A.NODECOUNT
AND B.GRDCOLUMNCOUNT = A.GRDCOLUMNCOUNT
AND B.GRDSHOWCOLHDG = A.GRDSHOWCOLHDG
AND B.GRDSHOWROWHDG = A.GRDSHOWROWHDG
AND B.GRDCOLHDGSTYLE = A.GRDCOLHDGSTYLE
AND B.GRDODDROWSTYLE = A.GRDODDROWSTYLE
AND B.GRDEVENROWSTYLE= A.GRDEVENROWSTYLE
AND B.GRDLBLMSGSET = A.GRDLBLMSGSET
AND B.GRDLBLMSGNUM = A.GRDLBLMSGNUM
AND B.GRDLBLALIGN = A.GRDLBLALIGN
AND B.GRDACTTYPE = A.GRDACTTYPE
AND B.GRDACTRECNAME = A.GRDACTRECNAME
AND B.GRDACTFIELDNAME= A.GRDACTFIELDNAME
AND B.GRDACTPNLNAME = A.GRDACTPNLNAME
AND B.SRC_TGT <> A.SRC_TGT)
ORDER BY A.FIELDTYPE,A.RECNAME,A.FIELDNAME,A.ONVALUE,A.SRC_TGT,A.LBLTEXT
GO
