USE SA76ACC
GO
CREATE VIEW XYXALFA_VW_NR AS
 /* Het uitsluiten van de lege menugroup is omdat peoplesoft de lege menugroup gebruikt voor popup menu's e.d. */
 SELECT A.MENUGROUP, B.MENUGROUP AS MENUGROUPLANG, A.GROUPORDER, COUNT(*) AS NR FROM PSMENUDEFN A FULL OUTER JOIN PSMENUDEFNLANG B ON (A.MENUNAME = B.MENUNAME)
 WHERE A.MENUGROUP <> ''
 GROUP BY A.MENUGROUP, B.MENUGROUP, A.GROUPORDER
GO
SELECT * FROM XYXALFA_VW_NR
 ORDER BY 1,2,3
GO
BEGIN TRAN

INSERT INTO PSMENUDEFNLANG (MENUNAME, LANGUAGE_CD, MENULABEL, MENUGROUP, DESCR, DESCRLONG)
SELECT A.MENUNAME, 'DUT' AS LANGUAGE_CD, A.MENULABEL, A.MENUGROUP, A.DESCR, A.DESCRLONG FROM PSMENUDEFN A
WHERE MENUNAME NOT IN (SELECT B.MENUNAME FROM PSMENUDEFNLANG B)
AND MENULABEL <> ''

UPDATE PSMENUDEFNLANG
SET MENUGROUP = VW.MENUGROUPLANG
FROM PSMENUDEFNLANG B, XYXALFA_VW_NR VW
WHERE B.MENUGROUP =  VW.MENUGROUP
AND B.MENUGROUP   <> VW.MENUGROUPLANG
AND B.MENUGROUP IN ('&Administer Workforce','&Manage Student Financials','Design &Student Administration')
AND B.MENUGROUP NOT IN ('PeopleSoft')

COMMIT
GO
BEGIN TRAN
UPDATE PSMENUDEFNLANG
SET MENUGROUP = VW.MENUGROUPLANG
--SELECT * 
FROM PSMENUDEFNLANG B, XYXALFA_VW_NR VW
WHERE B.MENUGROUP =  VW.MENUGROUP
AND B.MENUGROUP   <> VW.MENUGROUPLANG
AND B.MENUGROUP IN ('&Administer Workforce','&Manage Student Financials','Design &Student Administration','&Compensate Employees','&Self Service','Html Access')
AND B.MENUGROUP NOT IN ('PeopleSoft')
GO

SELECT * FROM XYXALFA_VW_NR
 ORDER BY 1,2,3

ROLLBACK
GO
DROP VIEW XYXALFA_VW_NR
GO







GO
/*
 SELECT B.* FROM PSMENUITEM A FULL OUTER JOIN PSMENUITEMLANG B
  ON (A.MENUNAME = B.MENUNAME
  AND A.BARNAME  = B.BARNAME
  AND A.ITEMNAME = B.ITEMNAME)
 WHERE A.MENUNAME IS NULL
*/
GO
/*
 SELECT DISTINCT A.NAME FROM SYSOBJECTS A JOIN SYSCOLUMNS B ON (A.ID = B.ID) 
 WHERE A.NAME LIKE 'PS%' ORDER BY A.NAME
*/
GO
/*
 SELECT A.MENUNAME, A.MENUGROUP, B.MENUGROUP, COUNT(*) FROM PSMENUDEFN A FULL OUTER JOIN PSMENUDEFNLANG B ON (A.MENUNAME = B.MENUNAME)
 GROUP BY A.MENUNAME, A.MENUGROUP, B.MENUGROUP
 ORDER BY 1,2,3
*/
GO
/*
 SELECT A.MENUGROUP, A.GROUPORDER, B.GROUPORDER, COUNT(*) AS NR FROM PSMENUDEFN A FULL OUTER JOIN PSMENUDEFN B ON (A.MENUGROUP = B.MENUGROUP)
 GROUP BY A.MENUGROUP, A.GROUPORDER, B.GROUPORDER
 ORDER BY 1,2,3
*/
GO
/*
 UPDATE PSMENUDEFN
 SET GROUPORDER = '9994'
 WHERE MENUGROUP  = '&Compensate Employees'
  AND GROUPORDER = '3'
--
 UPDATE PSMENUDEFN
 SET GROUPORDER = '9991'
 WHERE MENUGROUP  = '&Develop Workforce'
   AND GROUPORDER = '2'
--
 UPDATE PSMENUDEFN
 SET GROUPORDER = '9991'
 WHERE MENUGROUP  = '&Develop Workforce'
   AND GROUPORDER = '9992'
--
 UPDATE PSMENUDEFN
 SET GROUPORDER = '9995'
 WHERE MENUGROUP  = 'Monitor &Workplace'
   AND GROUPORDER = '4'
--
 UPDATE PSMENUDEFN
 SET GROUPORDER = '9995'
 WHERE MENUGROUP  = 'Monitor &Workplace'
   AND GROUPORDER = '9994'
--
--
 BEGIN TRAN
 UPDATE PSMENUDEFN
 SET GROUPORDER = '9995'
 WHERE MENUGROUP  = 'Monitor &Workplace'
   AND GROUPORDER = '9994'
 ROLLBACK
 COMMIT
*/
GO
/*
 SELECT DISTINCT A.BARLABEL, B.BARLABEL, B.LANGUAGE_CD FROM PSMENUITEM A FULL OUTER JOIN PSMENUITEMLANG B
 ON (A.MENUNAME = B.MENUNAME)
 ORDER BY 3,1,2
*/
GO
/*
 SELECT DISTINCT A.ITEMLABEL, B.ITEMLABEL, B.LANGUAGE_CD FROM PSMENUITEM A FULL OUTER JOIN PSMENUITEMLANG B
 ON (A.MENUNAME = B.MENUNAME)
 ORDER BY 3,1,2
*/
GO
/*
 UPDATE PSMENUDEFNLANG
 SET MENUGROUP = 'Personeels&beheer'
 WHERE MENUGROUP = '&Administer Workforce'
--
 UPDATE PSMENUDEFNLANG
 SET MENUGROUP = '&Personeelsmanagement'
 WHERE MENUGROUP = '&Develop Workforce'
--
 UPDATE PSMENUDEFNLANG
 SET MENUGROUP = 'Finan&ciële Studentenadmin.'
 WHERE MENUGROUP = '&Manage Student Financials'
--
 UPDATE PSMENUDEFNLANG
 SET MENUGROUP = '&Selfservice'
 WHERE MENUGROUP = '&Self Service'
--
 UPDATE PSMENUDEFNLANG
 SET MENUGROUP = 'Studentenadmin. ont&werpen'
 WHERE MENUGROUP = 'Design &Student Administration'
--
 UPDATE PSMENUDEFNLANG
 SET MENUGROUP = '&Bedrijfsinstellingen'
 WHERE MENUGROUP = 'PeopleSoft'
--
 UPDATE PSMENUDEFNLANG
 SET MENUGROUP = '&Arbeidsomstandigheden'
 WHERE MENUGROUP = 'Monitor &Workplace'
--
--
 BEGIN TRAN
 UPDATE PSMENUDEFNLANG
-- SET MENUGROUP = 'HTML-toegang'
-- WHERE MENUGROUP = '&EDI Manager'
 ROLLBACK
 COMMIT
*/