USE SA76TRN
GO
--SELECT * FROM SYSOBJECTS WHERE NAME LIKE 'PSP%'
--GO
SELECT PPD.PROJECTNAME, PAD.PNLNAME, PAD.LANGUAGE_CD FROM PSPROJECTDEFN PPD JOIN PSPROJECTITEM PPI
  ON (PPD.PROJECTNAME  =    PPI.PROJECTNAME) LEFT OUTER JOIN PSPNLDEFN PAD
  ON (PPI.OBJECTVALUE1 =    PAD.PNLNAME AND PPI.OBJECTVALUE2 = PAD.LANGUAGE_CD)
WHERE PPD.PROJECTNAME  LIKE 'U017%'
  AND PPI.OBJECTTYPE   =    5
ORDER BY PPD.PROJECTNAME, PPI.OBJECTTYPE
GO
USE SA76TRN
GO
SELECT * 
FROM SYSOBJECTS
WHERE NAME LIKE 'PSPROJ%'
GO
SELECT PPD.PROJECTNAME, PPI.* 
FROM PSPROJECTDEFN PPD JOIN PSPROJECTITEM PPI
  ON (PPD.PROJECTNAME = PPI.PROJECTNAME)
WHERE PPD.PROJECTNAME LIKE 'U017%' AND PPD.PROJECTNAME > 'U017_'
ORDER BY PPD.PROJECTNAME
-- ---------------------------------------------------------------------------
-- --- Deel Twee
-- ---------------------------------------------------------------------------
USE SA76UPD
GO
SELECT DISTINCT A.NAME FROM SYSOBJECTS A JOIN SYSCOLUMNS B ON (A.ID = B.ID) 
WHERE A.NAME LIKE 'PS%' 
ORDER BY A.NAME
GO
--SELECT A.MENUNAME, A.MENUGROUP, B.MENUGROUP, COUNT(*) FROM PSMENUDEFN A FULL OUTER JOIN PSMENUDEFNLANG B ON (A.MENUNAME = B.MENUNAME)
--GROUP BY A.MENUNAME, A.MENUGROUP, B.MENUGROUP
--ORDER BY 1,2,3
--GO
--SELECT A.MENUGROUP, A.GROUPORDER, B.GROUPORDER, COUNT(*) FROM PSMENUDEFN A FULL OUTER JOIN PSMENUDEFN B ON (A.MENUGROUP = B.MENUGROUP)
--GROUP BY A.MENUGROUP, A.GROUPORDER, B.GROUPORDER
--ORDER BY 1,2,3
--GO
--BEGIN TRAN
--UPDATE PSMENUDEFN
--SET GROUPORDER = '9994'
--WHERE MENUGROUP  = '&Compensate Employees'
--  AND GROUPORDER = '3'
--COMMIT
--ROLLBACK
--GO

SELECT * FROM PSPROJECTITEM A
WHERE A.PROJECTNAME like 'AC_KPP%' AND A.OBJECTTYPE = '5'
ORDER BY 1

SELECT DISTINCT MENUGROUP = CASE WHEN AL.MENUGROUP IS NULL THEN A.MENUGROUP
	ELSE AL.MENUGROUP END, 
 	MENULABEL = CASE WHEN AL.MENULABEL IS NULL THEN A.MENULABEL
	ELSE AL.MENULABEL END, A.MENUNAME,
	BARLABEL = CASE WHEN BL.BARLABEL IS NULL THEN B.BARLABEL
	ELSE BL.BARLABEL END,
	ITEMLABEL = CASE WHEN BL.ITEMLABEL IS NULL THEN B.ITEMLABEL
	ELSE BL.ITEMLABEL END, C.ITEMNAME
FROM PSMENUDEFN A LEFT OUTER JOIN PSMENUDEFNLANG AL 
    ON (A.MENUNAME   = AL.MENUNAME)  JOIN (PSMENUITEM   B LEFT OUTER JOIN PSMENUITEMLANG BL 
      ON (B.MENUNAME   = BL.MENUNAME   AND B.BARNAME = BL.BARNAME AND B.ITEMNAME = BL.ITEMNAME))
    ON (A.MENUNAME   = B.MENUNAME)   JOIN (PSPNLGROUP   C LEFT OUTER JOIN PSPNLGROUPLANG CL
      ON (C.PNLGRPNAME = CL.PNLGRPNAME AND C.MARKET  = CL.MARKET AND C.PNLNAME = CL.PNLNAME))
    ON (B.ITEMNAME   = C.ITEMNAME)   JOIN (PSPNLGRPDEFN D LEFT OUTER JOIN PSPNLGDEFNLANG DL 
      ON (D.PNLGRPNAME = DL.PNLGRPNAME AND D.MARKET  = DL.MARKET))
    ON (C.PNLGRPNAME = D.PNLGRPNAME) JOIN PSPNLDEFN     E
    ON (C.PNLNAME    = E.PNLNAME)    JOIN PSPROJECTITEM F
    ON (E.PNLNAME    = F.OBJECTVALUE1 AND F.OBJECTTYPE = '5')
WHERE F.PROJECTNAME like 'AC_KPP%'
ORDER BY 1,2,3,4



