USE SA76PRO
GO
SELECT A.*, '---', B.* 
FROM SYSOBJECTS A JOIN SYSCOLUMNS B 
	ON (A.ID = B.ID) 
WHERE A.TYPE = 'U'
ORDER BY 1

SELECT 'SELECT TOP 100'''+A.NAME+''' AS TABLE, '+B.NAME+' FROM '+A.NAME   
FROM SYSOBJECTS A JOIN SYSCOLUMNS B 
	ON (A.ID = B.ID) 
WHERE A.TYPE = 'U' 
ORDER BY 1
