USE KPP_TEL
GO
SELECT A.* FROM sysobjects A
WHERE A.status >= 0 
AND A.parent_obj =0
ORDER BY A.name
GO
SELECT B.* FROM sysobjects A JOIN syscolumns B
  ON (A.id = B.id)
WHERE A.status >= 0 
AND A.parent_obj =0
ORDER BY A.id, B.name
GO

CREATE TABLE ACTABLES(NAME CHAR(20),
	DESCR CHAR(255))

CREATE TABLE PERSON_DATA(PERSON_ID CHAR(12),
  EFFDT DATETIME,
  EFF_STATUS CHAR(1),
  FIRSTNAME CHAR(30),
  NAME CHAR(30),
  PREFIX CHAR(12),
  GENDER CHAR(1),
  BIRTHDATE DATETIME,
  BIRTHPLACE CHAR(12),
  TELEPHONE CHAR(20))

CREATE TABLE LOCATION(ORGANIZATION_ID CHAR(12),
  LOCATION_ID CHAR(12),
  EFFDT DATETIME,
  EFF_STATUS CHAR(1),
  SHORTNAME CHAR(10),
  NAME CHAR(30),
  FIRSTCONTACT CHAR(12))

CREATE TABLE PERSON(PERSON_ID CHAR(12),
  EFFDT DATETIME,
  EFF_STATUS CHAR(1))

CREATE TABLE ORGANIZATION(ORGANIZATION_ID CHAR(12),
  EFFDT DATETIME,
  EFF_STATUS CHAR(1),
  SHORTNAME CHAR(10),
  NAME CHAR(30),
  FIRSTLOCATION CHAR(12),
  FIRSTCONTACT CHAR(12))

/*
SELECT * FROM sysobjects WHERE name LIKE 'AC%'
SELECT * FROM ACTABLES
SELECT * FROM ACSYSOBJECTS WHERE NAME LIKE 'AC%' 
*/
GO
SELECT * FROM AC_TEL_TOESTEL_TBL ORDER BY TOESTEL_ID

SELECT A.LOK_ID, A.KAMER_ID, A.OUTLET_ID, A.OUTLET_TYPE, C.SHORTDESC, A.TELEFOONNR, A.TOESTEL_ID, B.NAME, A.PERS_ID
 FROM AC_UTP_OUTLET_TBL A LEFT OUTER JOIN AC_TEL_TOESTEL_TBL B
  ON (A.TOESTEL_ID = B.TOESTEL_ID) LEFT OUTER JOIN ACXLINK C
  ON (C.FIELDNAME = 'OUTLET_TYPE' AND (A.OUTLET_TYPE = C.FIELDVALUE))
ORDER BY LOK_ID, OUTLET_ID
GO
/*
INSERT INTO AC_TEL_TOESTEL_TBL VALUES ('A000', 'Onbekend', 'Analoog', 'Analoog toestel')
DELETE FROM AC_UTP_OUTLET_TBL WHERE OUTLET_ID = 'E18'
*/
GO
/* -- LOK_ID, OUTLET_ID, OUTLET_TYPE, KAMER_ID, TELEFOONNR, TOESTEL_ID 
INSERT INTO AC_UTP_OUTLET_TBL VALUES ('HORA','021','E11','I','3017','I000','WIP')
INSERT INTO AC_UTP_OUTLET_TBL VALUES ('HORA','021','F12','D','','', '')
INSERT INTO AC_UTP_OUTLET_TBL VALUES ('HORA','019','E23','I','3042','I003','VAS')
INSERT INTO AC_UTP_OUTLET_TBL VALUES ('HORA','021','E14',' ','','', '')
*/
GO

